### ISSUE TITLE
Add error on non curly scope

### ISSUE THREAD

**Issue by tomasfrancisco** [lightbasenl/eslint-config-lightbase#3]
I highly recommend to add 
```json
{
    "curly": "error"
}
```

This way it's prevented to have code like
```typescript
if (something) runAction1(); runArction2();
```
When in reality this code should have been written like:
```typescript
if (something) runAction1(); 
runArction2();
```

**Comment by owinter86** [comment]
We already have it in the community react native eslint, seems like the CRA eslint doesnt have it though.

https://github.com/facebook/react-native/blob/01abcf0e83fe58757661dcf6cfc0c2843fed570d/packages/eslint-config-react-native-community/index.js#L139

**Comment by tomasfrancisco** [comment]
I'll make a PR for that then ;)

**Comment by tomasfrancisco** [comment]
I believe this was added meanwhile by you @owinter86? Reopen if still needed.
